version: '3.9'

services:
  web:
    container_name: simplenewsreader
    build: 
      context: .
      dockerfile: src/Presentation/SimpleNewsReader.WebApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5000:80"
      - "5001:443"
    depends_on:
      - migrations
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql2019
    environment:
      - SA_PASSWORD=Test@dmin123
      - ACCEPT_EULA= "Y"
    ports:
      - "4433:1433"
    depends_on:
      - migrations

  migrations:
    build: 
      context: .
      dockerfile: src/Presentation/SimpleNewsReader.WebApi/Migrations.Dockerfile